---
title: "Simple matrix example"
output: html_document
date: "2025-02-28"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
set.seed(42)
```

## Lille eksempel
```{r}
x <- c(1,2,4, 8)
D <- as.matrix(dist(x, diag = T, upper = T))
sig_kernel = 2
W <- exp(-D^2/(2*sig_kernel^2))
diag(W) = 0
lam_k = 2

rowsums = rowSums(W)
sigmas = lam_k/rowsums

W_tilde = sweep(W, 1, FUN = '/', STATS = rowsums)

phi = 0.5


Q_k = diag(1/sigmas) %*% (diag(4) - phi*W_tilde)

```


## Større eksempel
```{r}
x <- c(1.5, 2, 2, 2, 6, 6, 6.5)
y <- c(2, 1.5, 2, 6, 6.5, 6, 6)

df <- data.frame(
  x = x,
  y = y,
  label = paste0("x[", 1:7, "]")
)

ggplot(df, aes(x = x, y = y)) +
  geom_point(size = 2.5) +
  geom_text(aes(label = label), parse = TRUE, hjust = -0.5, color = "darkred", size = 4) +
  labs(x = "x", y = "y") +
  xlim(min(df$x) - 1, max(df$x) + 1) +
  ylim(min(df$y) - 1, max(df$y) + 1) +
  theme_minimal()
```

```{r}
D <- as.matrix(dist(cbind(x,y), diag = T, upper = T))
sig_kernel = 0.5
W <- exp(-D^2/2*sig_kernel^2)
diag(W) = 0
lam_k = 2

rowsums = rowSums(W)
sigmas = lam_k/rowsums

W_tilde = sweep(W, 1, FUN = '/', STATS = rowsums)

phi = 0.9


Q_k = diag(1/sigmas) %*% (diag(7) - phi*W_tilde)
```


```{r}
library(colorspace)
data_plot <- Q_k %>% as_tibble() %>% rownames_to_column("Var1") %>% 
  pivot_longer(-Var1, names_to = "Var2", values_to = "value") %>% 
  mutate(
    Var1 = factor(Var1, levels = 1:7),
    Var2 = factor(Var2, levels = 7:1)
  ) 

max_val <- max(abs(data_plot$value))

ggplot(data_plot, aes(Var1, Var2)) +
  geom_tile(aes(fill = value)) + 
  geom_text(aes(label = round(value, 3)), size = 3.5) + 
  scale_fill_gradientn(
    colours = c("dodgerblue", "white", "darkorange"),
    values = c(0, 0.3, 1)
  ) +
  theme_minimal() +
  labs(x = '', y= '') +
  theme(legend.title = element_blank()) + 
  theme(legend.position ="none")
  
```



