---
title: "Circulant GMRF"
output: html_document
date: "2025-02-17"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Simulating from a 1st-order circulant GMRF

```{r}
circulant_matrix_base = function(kappa, beta, N ) {
  diag_entry = kappa
  remainder = c(kappa*beta, 
                rep(0, N-1-2), 
                kappa*beta)
  return( c(diag_entry, remainder) )
}

create_circulant_precision_matrix = function(kappa, beta, N = 10) {
  base = circulant_matrix_base(kappa, beta, N)
  N = length(base)
  idx = outer(seq_len(N), seq_len(N), function(i,j) ((j-i) %% N) +1)  # Definition 2.4 Rue & Held
  matrix_out = matrix(base[idx], nrow = N)
  return (matrix_out)
}

simulate_circulant_GMRF = function(mu, precision_mat, nsim = 1) {
  Q = precision_mat
  N = nrow(Q)
  Sigma = solve(Q) 
  out = MASS::mvrnorm(n = nsim, mu = rep(mu, N), Sigma = Sigma)
  return(out)
}


# N = 64
# Q = create_circulant_precision_matrix(100, -0.45, N = N)
# 
# mu = 5
# V = simulate_circulant_GMRF(mu, Q)
# plot(V, type = 'b')
```

### Varying kappa and beta - plot

```{r}
set.seed(3)
plot_data_for_gmrf <- function(kappa, beta,mu=5, N=32) {
  Q = create_circulant_precision_matrix(kappa, beta, N)
  V = simulate_circulant_GMRF(mu, Q, nsim = 1) 
  
  V_ = c(V, V[1])
  
  theta <- seq(0, 2*pi, length.out = N + 1)

  x <- V_ * cos(theta)
  y <- V_ * sin(theta)
  
  
  plot_data <- data.frame(x = x, 
                          y = y, 
                          theta = theta, 
                          kappa = factor(kappa), 
                          beta = factor(beta))
  return(plot_data)
}


betas = c(0, -0.15, -0.3, -0.45)
kappas = c(1, 2, 4)

params = expand.grid(kappa = kappas, beta = betas)
mu_plot = 6
df_all <- pmap_dfr(params, function(kappa, beta) {
  plot_data_for_gmrf(kappa, beta, mu =mu_plot, N = 50)
})
```

```{r}
mu = mu_plot
df_all %>% 
  ggplot() + 
  geom_path(aes(x = x, y = y)) +
  geom_path(aes(x = mu*cos(theta), y = mu*sin(theta)), lty = 'dashed', alpha = 0.5) + 
  coord_fixed() + 
  facet_grid(kappa~beta, scales = 'fixed') + 
  labs(
    y=latex2exp::TeX(r'($\kappa$)'),
    x=latex2exp::TeX(r'($\beta$)'),
  ) +
  theme_minimal() +
  
  theme(
    axis.text = element_blank(),  
    axis.ticks = element_blank()   
  )
```


## GMRF model likelihood

### Solving all parameters numerically
```{r}
N = 128
Q = create_circulant_precision_matrix(kappa=2, beta=0.05, N = N)
mu = 5
V = simulate_circulant_GMRF(mu, Q)

gmrf_neg_likelihood <- function(th) {
  mu = mean(V)
  bet = th[1]
  kap = th[2]
  
  term1 = 1/2*(N*log(kap) + sum(log(1+2*bet*cos(2*pi*seq(0,N-1)/N))))
  term2 = -1/2*kap*sum((V-mu)^2)
  
  cross_term = 0
  for (i in seq(1,N-1)) {
    to_add = (V[i] - mu)*(V[i+1]-mu)
    cross_term = cross_term + to_add
  }
  cross_term = cross_term + (V[1]-mu)*(V[N]-mu)
  term3 = -kap*bet*cross_term
  
  ll = term1 + term2 + term3
  return(-ll)
}


#parametre: mu=5, beta=0.05, kappa=2
# optim(c(0.01, 5), gmrf_neg_likelihood, 
#       lower = c(0.01, 1), 
#       upper = c(0.49, 6),
#       method = 'L-BFGS-B',
#       #method = 'SANN',
#       control = list(maxit = 100000)
#       )
```


### Solving for beta numerically
```{r}
N = 256
Q = create_circulant_precision_matrix(kappa=2, beta=-0.3, N = N)
mu = 5
V = simulate_circulant_GMRF(mu, Q)
mu_est = mean(V)


S <- sum((V - mu_est)^2) 


R_val = 0
  for (i in seq(1,N-1)) {
    to_add = (V[i] - mu_est)*(V[i+1]-mu_est)
    R_val = R_val + to_add
  }
  R_val = R_val + (V[1]-mu_est)*(V[N]-mu_est)

## Score equation for beta 
f <- function(beta) {
  j <- 0:(N-1)
  lhs <- sum( cos(2*pi*j/N) / (1 + 2*beta*cos(2*pi*j/N)) )
  rhs <- (N * R_val) / (S + 2*beta*R_val)
  return(lhs - rhs)
}

result <- uniroot(f, lower = -0.49, upper = 0.49)
beta_est <- result$root

# Now compute kappa using the expression derived:
kappa_est <- N / (S + 2*beta_est*R_val)

c(mu_est, kappa_est, beta_est)
```


